### ISSUE TITLE
Templating and localization with react js

### ISSUE THREAD

**Issue by quarterpi** [krakenjs/kraken-example-with-shoppingcart#29]
Is there a reason one would choose anemone-machina and anemone-lingua over makara and luska when integrating with react js?

**Comment by grawk** [comment]
Honestly wouldn't recommend following this example right now. It was put together while our react strategy was not really determined.

**Comment by quarterpi** [comment]
Is there another example I should be looking at, or am I on my own for right now?

**Comment by grawk** [comment]
Internally at PayPal we are using "react-engine" (which is identical to anemone-machina) and folks are also using a few other SPA patterns that don't require server renders. I'll try and get this example replaced soon, but I don't have an ETA for you right now.

**Comment by quarterpi** [comment]
Okay, I’ll have a look at react-engine. Thank you
