### ISSUE TITLE
Problem with cart

### ISSUE THREAD

**Issue by senseialex** [krakenjs/kraken-example-with-shoppingcart#3]
Hi, when I add some product to cart, the program crash, can someone help me?

**Comment by aredridel** [comment]
What sort of crash do you get? Do you get an error message?

**Comment by senseialex** [comment]
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@1.3.14
3 info using node@v0.10.22
4 verbose node symlink C:\Program Files\nodejs\\node.exe
5 verbose run-script [ 'prestart', 'start', 'poststart' ]
6 info prestart kraken-examples-with.shoppingcart@0.1.0
7 info start kraken-examples-with.shoppingcart@0.1.0
8 verbose unsafe-perm in lifecycle true
9 info kraken-examples-with.shoppingcart@0.1.0 Failed to exec start script
10 error kraken-examples-with.shoppingcart@0.1.0 start: `node index.js`
10 error Exit status 1
11 error Failed at the kraken-examples-with.shoppingcart@0.1.0 start script.
11 error This is most likely a problem with the kraken-examples-with.shoppingcart package,
11 error not with npm itself.
11 error Tell the author that this fails on your system:
11 error     node index.js
11 error You can get their info via:
11 error     npm owner ls kraken-examples-with.shoppingcart
11 error There is likely additional logging output above.
12 error System Windows_NT 6.2.9200
13 error command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
14 error cwd C:\Users\Alejandro\Documents\kraken-example-with-shoppingcart-master
15 error node -v v0.10.22
16 error npm -v 1.3.14
17 error code ELIFECYCLE
18 verbose exit [ 1, true ]
```

When I click on view cart it crash. I dont know why

**Comment by senseialex** [comment]
![111](https://cloud.githubusercontent.com/assets/7697608/7904787/69554bd8-07cf-11e5-8ef2-472410fd4fd9.PNG)

**Comment by aredridel** [comment]
Oh goodness. It looks like you're running into one of the double-callback bugs. I thought I'd stomped all of those.

However, you're also running an old node and npm -- can you try updating to latest (at least latest node 0.10) and latest npm, running `npm update`, and trying again?

**Comment by senseialex** [comment]
I update the npm and the node but the same thing when i add to cart 
![113](https://cloud.githubusercontent.com/assets/7697608/7905313/00b7f564-07dc-11e5-9baf-e15f6605b950.PNG)
![114](https://cloud.githubusercontent.com/assets/7697608/7905314/00bafb1a-07dc-11e5-9416-7f414e52e6f9.PNG)
![112](https://cloud.githubusercontent.com/assets/7697608/7905316/036034e8-07dc-11e5-9e89-4e4249d24ff9.PNG)

**Comment by senseialex** [comment]
The bson have problems :s

**Comment by aredridel** [comment]
try `npm rebuild` to make sure your modules match the version of node.

**Comment by glasermeister** [comment]
Hi there, thanks for working on this excellent looking project.  I've also upgraded my NodeJS and rebuilt the modules to the latest release and gone through the steps above, however there still seems to be a double callback in the cart.  In the code:

try {
				var compiled = that.dust.compile(bundleBuffer.toString(), cacheKey);
				that.dust.loadSource(compiled);
				return dustRender(cacheKey, config.model, cb);
			} catch (dustErr) {
				console.log(dustErr);
			}

in dust.js it errors out with [Error: Callback was already called.] when doing a GET on the /cart path.  - could you please advise what the solution could be?

**Comment by aredridel** [comment]
Just a note here: bson not compiling is fine, it falls back to a pure JS version and will still work.
