### ISSUE TITLE
connection error: [Error: failed to connect to [localhost:27017]]

### ISSUE THREAD

**Issue by thekennysong** [krakenjs/kraken-example-with-shoppingcart#4]
X-5s-MacBook-Air:kraken-example-with-shoppingcart x_5$ sudo npm start

> kraken-examples-with.shoppingcart@0.1.0 start /Users/x_5/kraken-example-with-shoppingcart
> node index.js

[development] Listening on http://localhost:8000
connection error: [Error: failed to connect to [localhost:27017]]

**Comment by grawk** [comment]
Hi @thekennysong. You would see this error if you don't have mongodb running locally. Please make sure you have mongodb running prior to running the application:
https://github.com/krakenjs/kraken-example-with-shoppingcart#prerequisites
