### ISSUE TITLE
Double callback in dust.js when viewing /cart page

### ISSUE THREAD

**Issue by Ampakinetic** [krakenjs/kraken-example-with-shoppingcart#6]
I've upgraded my NodeJS and rebuilt the modules to the latest release, however there seems to be a double callback in the cart. In the code:

```
try {
    var compiled = that.dust.compile(bundleBuffer.toString(), cacheKey);
    that.dust.loadSource(compiled);
    return dustRender(cacheKey, config.model, cb);
} catch (dustErr) {
    console.log(dustErr);
}
```

in dust.js it errors out with `[Error: Callback was already called.]` when doing a GET on the /cart path. - could you please advise what the solution could be?

**Comment by aredridel** [comment]
Where in the code are you seeing this? I'm not quite sure which part is erroring out for you. I can't replicate it, but that's not surprising since you're getting an error.

**Comment by Ampakinetic** [comment]
Thanks for your response.  I've just now done a fresh get from the repo and ran npm install with recent copy of Node. The full log is here:

```
[development] Listening on http://localhost:8000
db connection open
::1 - - [22/Jul/2015:13:39:04 +0000] "GET / HTTP/1.1" 200 1628 "-" "Mozilla/5.0
(Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.
89 Safari/537.36"
Wed, 22 Jul 2015 13:39:07 GMT uncaughtException Callback was already called.
Error: Callback was already called.
    at E:\Downloads\kraken-example-with-shoppingcart-master\kraken-example-with-
shoppingcart-master\node_modules\bundalo\node_modules\async\lib\async.js:22:31
    at E:\Downloads\kraken-example-with-shoppingcart-master\kraken-example-with-
shoppingcart-master\node_modules\bundalo\node_modules\async\lib\async.js:530:21
    at handleBundleBuffer (E:\Downloads\kraken-example-with-shoppingcart-master\
kraken-example-with-shoppingcart-master\node_modules\bundalo\bundler\dust.js:69:
12)
    at fs.js:334:14
    at E:\Downloads\kraken-example-with-shoppingcart-master\kraken-example-with-
shoppingcart-master\node_modules\bundalo\node_modules\file-resolver\node_modules
\graceful-fs\graceful-fs.js:104:5
    at E:\Downloads\kraken-example-with-shoppingcart-master\kraken-example-with-
shoppingcart-master\node_modules\engine-munger\node_modules\graceful-fs\graceful
-fs.js:104:5
    at FSReqWrap.oncomplete (fs.js:95:15)

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs
\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE
npm ERR! kraken-example-with-shoppingcart@0.1.0 start: `node index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the kraken-example-with-shoppingcart@0.1.0 start script 'node
 index.js'.
npm ERR! This is most likely a problem with the kraken-example-with-shoppingcart
 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node index.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls kraken-example-with-shoppingcart
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     E:\Downloads\kraken-example-with-shoppingcart-master\kraken-example
-with-shoppingcart-master\npm-debug.log
```

**Comment by aredridel** [comment]
Well nuts. Definitely looks like a double-callback bug in bundalo.

**Comment by Ampakinetic** [comment]
Does it not happen on your system with a fresh install?  Could it be data related? I've just setup a bunch of random products, but maybe that's the difference if you're not seeing the same result.

**Comment by aredridel** [comment]
Yeah, doesn't happen for me at all.

**Comment by Ampakinetic** [comment]
Ok I have restarted MongoDB with a completely blank data folder, and even without products it crashes the same way as soon as I click on the View Cart link in the header.

Running on 64bit Win 7 with SSD drive

**Comment by aredridel** [comment]
Which version of node are you using?

**Comment by Ampakinetic** [comment]
node v0.12.7
npm  v2.11.3

**Comment by aredridel** [comment]
Hm, same. I may have to fire up a windows VM and see if that's the issue.

**Comment by Ampakinetic** [comment]
Ok thanks, I use Windows for running Visual Studio.  I can try it on Linux as well but it'd be nice if it worked on both.

**Comment by aredridel** [comment]
Definitely! I'd love to know if that fixes it for you.

**Comment by Ampakinetic** [comment]
Ok will try it.  Another thing is I can't use Git to get the Repo:

```
C:\Work\Prog\Node\kraken-example-with-shoppingcart-master\kraken-example-with-sh
oppingcart-master\git>git clone git@github.com:krakenjs/kraken-example-with-shop
pingcart.git
Cloning into 'kraken-example-with-shoppingcart'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

---

So I'm downloading the ZIP file instead.  Is there a difference?

**Comment by aredridel** [comment]
There shouldn't be, but you can just use the public URL for the repo instead of that private one. `git@` is SSH, for developers, `git://` or `https://` are public.

**Comment by aredridel** [comment]
Which zip are you downloading?

**Comment by Ampakinetic** [comment]
https://github.com/krakenjs/kraken-example-with-shoppingcart/archive/master.zip

**Comment by aredridel** [comment]
Ah, okay. Should be fine, but I don't know the details of what if anything Windows will do while unpacking that.

**Comment by Ampakinetic** [comment]
I'm using WinRar, everything seems normal during and after install apart from the crash

**Comment by aredridel** [comment]
Then I'll have to take a look on Windows. bundalo _does_ have some nasty hacks for windows paths that could be done better, so I may just go find a bug.

**Comment by Ampakinetic** [comment]
Ok cool thanks, in the mean time I'll try it on Linux and report back asap

**Comment by aredridel** [comment]
Thank you!

**Comment by Ampakinetic** [comment]
Yes it works well on Linux, so must be a Windows only bug

**Comment by aredridel** [comment]
Alright! thanks for the tracing -- I'll peek at it and see if I can nail down that bug. I have my suspicions.

**Comment by Ampakinetic** [comment]
Ok cheers, looking forward to having it running on my dev box

**Comment by aredridel** [comment]
Boom. Replicated under Windows.

**Comment by aredridel** [comment]
And it looks like this is fixed by the pending changes in bundalo master that were yet to be published; that's bundalo@0.2.10 now. Update, and let me know if that doesn't work and I'll reopen this, but it should be solved for you.

**Comment by Ampakinetic** [comment]
Cool, thank you that fixed it.

**Comment by aredridel** [comment]
You are welcome!

**Comment by Ampakinetic** [comment]
Quick question, is the delete button meant to work?  I can't seem to delete products on either Windows  or Linux at the moment.

**Comment by aredridel** [comment]
y'know, I've not tried it! It might well be broken. A couple of these demos were written hastily!
